### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by CyberDudeJ** [django-files/django-files#173]
### Error Desc:
CSRF verification failed. Request aborted.

Cannot delete files, cannot set some settings, etc etc

**Comment by CyberDudeJ** [comment]
P.S. I am hosting through a reverse proxy with NGINX proxy manager

**Comment by smashedr** [comment]
Off the top of my head I can't think of what could be causing this, other than maybe a domain name mismatch somewhere, or possibly the nginx configuration. We would be glad to assist; however, need some more information.

Can you provide us with the following?

- Logs from Django
- Logs from Browser Console
- Nginx Configuration
- Domain(s) being used and any domains set in the .env file

**Comment by raluaces** [comment]
Going to close this out as stale since we have not heard back and are unable to reproduce this.
